/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controladores.ArrayArticulos;
import javax.swing.ImageIcon;

/**
 *
 * @author Hime
 */
public class Buscar extends javax.swing.JDialog {

    /**
     * Creates new form Buscar
     * @param parent
     * @param modal
     */
    public Buscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.gif")).getImage());
        } catch (Exception ex) {
            Mensajes.instance.mostrarMensaje("Icono invalido", "No se pudo cargar el icono de la aplicacion.", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ltArticulos = new javax.swing.JList();
        btnBuscar = new javax.swing.JButton();
        txBuscar = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar articulo");
        setResizable(false);

        ltArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ltArticulos.setName("ltArticulos"); // NOI18N
        ltArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltArticulosClickLista(evt);
            }
        });
        jScrollPane2.setViewportView(ltArticulos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbNombre.setText("Nombre del articulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ltArticulosClickLista(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltArticulosClickLista
        EditarArticulos ventana = new EditarArticulos(null, true, ltArticulos.getSelectedValue().toString());
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);

        ltArticulos.setListData(ArrayArticulos.getIntancia().getArticulostoArray());
    }//GEN-LAST:event_ltArticulosClickLista

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!txBuscar.getText().trim().equals("")) {
            ltArticulos.setListData(ArrayArticulos.getIntancia().buscarArticulo(txBuscar.getText()));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JList ltArticulos;
    private javax.swing.JTextField txBuscar;
    // End of variables declaration//GEN-END:variables
}
