/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controladores.ArrayArticulos;
import controladores.ArrayProveedores;
import javax.swing.ImageIcon;
import objetos.Articulo;
import objetos.Proveedor;

/**
 *
 * @author Hime
 */
public class EditarArticulos extends javax.swing.JDialog {

    private Articulo a;

    /**
     * Creates new form EditarArticulos
     *
     * @param parent
     * @param modal
     * @param articulo
     */
    public EditarArticulos(java.awt.Frame parent, boolean modal, String articulo) {
        super(parent, modal);
        initComponents();

        try {
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.gif")).getImage());
        } catch (Exception ex) {
            Mensajes.instance.mostrarMensaje("Icono invalido", "No se pudo cargar el icono de la aplicacion.", 0);
        }

        for (Proveedor p1 : ArrayProveedores.getIntancia().getProveedores()) {
            cbProveedores.addItem(p1);
        }

        String[] array = articulo.split(",");

        a = ArrayArticulos.getIntancia().buscarArticuloPorCodigo(array[0].substring(5));
        cargarArticulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbCamposRequeridos = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        lbPorcentaje = new javax.swing.JLabel();
        lbUnidadesCantidad = new javax.swing.JLabel();
        lbUnidadesReorden = new javax.swing.JLabel();
        lbProveedor = new javax.swing.JLabel();
        txDescripcion = new javax.swing.JTextField();
        lbImpuesto2 = new javax.swing.JLabel();
        lbCosto = new javax.swing.JLabel();
        txImpuesto2 = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        txImpuesto2Cantidad = new javax.swing.JTextField();
        txCosto = new javax.swing.JTextField();
        txCodigo = new javax.swing.JTextField();
        lbPrecioUnitario = new javax.swing.JLabel();
        txPrecioUnitario = new javax.swing.JTextField();
        lbImpuesto1 = new javax.swing.JLabel();
        cbProveedores = new javax.swing.JComboBox();
        txImpuesto1Cantidad = new javax.swing.JTextField();
        lbPorcentaje1 = new javax.swing.JLabel();
        lbLocalizacion = new javax.swing.JLabel();
        txImpuesto1 = new javax.swing.JTextField();
        txLocalizacion = new javax.swing.JTextField();
        ckPermiteDescripcionAlterna = new javax.swing.JCheckBox();
        lbCantidad = new javax.swing.JLabel();
        ckTieneNumeroSerie = new javax.swing.JCheckBox();
        txCantidad = new javax.swing.JTextField();
        lbNivelReorden = new javax.swing.JLabel();
        txNivelReorden = new javax.swing.JTextField();
        lbMonedaCosto = new javax.swing.JLabel();
        lbMonedaPrecioUnitario = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        txCategoria = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar articulos");
        setIconImage(null);
        setResizable(false);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbCamposRequeridos.setText("Los campos con el icono * son requeridos por el sistema");

        lbDescripcion.setText("Descripcion");

        txNombre.setToolTipText("Inserte el nombre");

        lbPorcentaje.setText("%");

        lbUnidadesCantidad.setText("unidades");

        lbUnidadesReorden.setText("unidades");

        lbProveedor.setForeground(new java.awt.Color(255, 0, 0));
        lbProveedor.setText("*Proveedor");

        lbImpuesto2.setText("Impuesto2:");

        lbCosto.setForeground(new java.awt.Color(255, 0, 0));
        lbCosto.setText("*Costo:");

        txImpuesto2.setToolTipText("Inserte el impuesto");

        lbCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lbCodigo.setText("*UPC/EAN/ISBN:");

        txImpuesto2Cantidad.setToolTipText("Inserte el impuesto");

        txCosto.setToolTipText("Inserte el costo");

        lbPrecioUnitario.setForeground(new java.awt.Color(255, 0, 0));
        lbPrecioUnitario.setText("*Precio unitario:");

        lbImpuesto1.setText("Impuesto1:");

        txImpuesto1Cantidad.setToolTipText("Inserte el impuesto");

        lbPorcentaje1.setText("%");

        lbLocalizacion.setText("Localizacion");

        txImpuesto1.setToolTipText("Inserte el impuesto");

        ckPermiteDescripcionAlterna.setText("Permite descripción alterna");

        lbCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lbCantidad.setText("*Cantidad:");

        ckTieneNumeroSerie.setText("El artículo tiene numero de serie");

        txCantidad.setToolTipText("Inserte la cantidad");

        lbNivelReorden.setForeground(new java.awt.Color(255, 0, 0));
        lbNivelReorden.setText("*Nivel de reorden:");

        lbMonedaCosto.setText("$");

        lbMonedaPrecioUnitario.setText("$");

        lbCategoria.setForeground(new java.awt.Color(255, 0, 0));
        lbCategoria.setText("*Categoria");

        lbNombre.setForeground(new java.awt.Color(255, 0, 0));
        lbNombre.setText("*Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCamposRequeridos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCerrar)
                                    .addComponent(btnCancelar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDescripcion)
                                .addGap(35, 35, 35)
                                .addComponent(txDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbCategoria)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lbCosto)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbMonedaCosto)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbImpuesto1)
                                                .addGap(34, 34, 34)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbCantidad)
                                            .addGap(36, 36, 36)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbLocalizacion)
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txImpuesto1Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbPorcentaje))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbUnidadesCantidad))
                                    .addComponent(txCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPrecioUnitario)
                                        .addGap(25, 25, 25)
                                        .addComponent(lbMonedaPrecioUnitario))
                                    .addComponent(lbNombre)
                                    .addComponent(lbProveedor)
                                    .addComponent(lbImpuesto2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txImpuesto2)
                                    .addComponent(txNombre)
                                    .addComponent(txPrecioUnitario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txImpuesto2Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbPorcentaje1))
                                    .addComponent(cbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckTieneNumeroSerie)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ckPermiteDescripcionAlterna)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbNivelReorden)
                                                .addGap(29, 29, 29)
                                                .addComponent(txNivelReorden, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbUnidadesReorden)))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigo)
                            .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProveedor)
                            .addComponent(lbCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMonedaCosto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCosto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbPrecioUnitario)
                                .addComponent(txPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMonedaPrecioUnitario)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbImpuesto1)
                            .addComponent(txImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbImpuesto2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txImpuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txImpuesto1Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPorcentaje))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCantidad)
                            .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txImpuesto2Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPorcentaje1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNivelReorden)
                            .addComponent(txNivelReorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUnidadesReorden)
                            .addComponent(lbUnidadesCantidad))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocalizacion)
                    .addComponent(txLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescripcion)
                    .addComponent(txDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckPermiteDescripcionAlterna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckTieneNumeroSerie)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCamposRequeridos))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NuevosArticulos ventana = new NuevosArticulos(null, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ArrayArticulos.getIntancia().eliminarArticulos(a);
        this.dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar ventana = new Buscar(null, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

            Articulo b = new Articulo();

            if(txCodigo.getText().trim().equals(""))
            {
                throw new Exception("El campo codigo esta incompleto.");
            }
            b.UPC = txCodigo.getText().trim();
            
            if(txNombre.getText().trim().equals(""))
            {
                throw new Exception("El nombre del articulo no ha sido especificado.");
            }
            b.nombre = txNombre.getText().trim();
            
            if(txCategoria.getText().trim().equals(""))
            {
                throw new Exception("La categoria del articulo no ha sido especificado.");
            }
            b.categoria = txCategoria.getText().trim();
            
            if(txCosto.getText().trim().equals(""))
            {
                throw new Exception("El costo del articulo no ha sido especificado.");
            }
            try {
                b.costo = Double.parseDouble(txCosto.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El costo es un campo numerico.");
            }
            
            if(txPrecioUnitario.getText().trim().equals(""))
            {
                throw new Exception("El precio unitario del articulo no ha sido especificado.");
            }
            try {
                b.precioUnitario = Double.parseDouble(txPrecioUnitario.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El precio unitario es un campo numerico.");
            }
            
            b.impuesto1 = txImpuesto1.getText().trim();
            try {
                b.impuesto1Cantidad = Double.parseDouble(0 + txImpuesto1Cantidad.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El impuesto de venta es un campo numerico.");
            }
            
            b.impuesto2 = txImpuesto2.getText().trim();
            try {
                b.impuesto2Cantidad = Double.parseDouble(0 + txImpuesto2Cantidad.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El impuesto de venta es un campo numerico.");
            }
            
            if(txCantidad.getText().trim().equals(""))
            {
                throw new Exception("La cantidad del articulo no ha sido especificado.");
            }
            try {
                 b.cantidad = Integer.parseInt(txCantidad.getText());
            } catch (NumberFormatException e) {
                throw new Exception("La cantidad  de venta es un campo numerico entero.");
            }
           
            if(txNivelReorden.getText().trim().equals(""))
            {
                throw new Exception("El nivel de reorden del articulo no ha sido especificado.");
            }
            try {
                 b.nivelReorden = Integer.parseInt(txNivelReorden.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El nivel de reorden es un campo numerico entero.");
            }
            
            b.localizacion = txLocalizacion.getText();
            b.descripcion = txDescripcion.getText();
            b.permitirDescripcionAlterna = ckPermiteDescripcionAlterna.isSelected();
            b.tieneNumeroSerie = ckTieneNumeroSerie.isSelected();

            b.proveedor = ArrayProveedores.getIntancia().devolverProveedor(cbProveedores.getSelectedIndex());

            ArrayArticulos.getIntancia().eliminarArticulos(a);
            ArrayArticulos.getIntancia().insertarArticulos(b);

            Mensajes.instance.mostrarMensaje("Operacion exitosa", "Datos guardados con exito", 1);
        } catch (Exception ex) {
            Mensajes.instance.mostrarMensaje(ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cargarArticulo();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cargarArticulo() {
        txCodigo.setText(a.UPC);
        txNombre.setText(a.nombre);
        txCategoria.setText(a.categoria);
        txCosto.setText("" + a.costo);
        txPrecioUnitario.setText("" + a.precioUnitario);
        txImpuesto1.setText("" + a.impuesto1);
        txImpuesto1Cantidad.setText("" + a.impuesto1Cantidad);
        txImpuesto2.setText("" + a.impuesto2);
        txImpuesto2Cantidad.setText("" + a.impuesto2Cantidad);
        txCantidad.setText("" + a.cantidad);
        txNivelReorden.setText("" + a.nivelReorden);
        txDescripcion.setText("" + a.descripcion);
        txLocalizacion.setText("" + a.localizacion);
        ckPermiteDescripcionAlterna.setSelected(a.permitirDescripcionAlterna);
        ckTieneNumeroSerie.setSelected(a.tieneNumeroSerie);
        cbProveedores.setSelectedIndex(ArrayProveedores.getIntancia().indiceProveedor(a.proveedor));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cbProveedores;
    private javax.swing.JCheckBox ckPermiteDescripcionAlterna;
    private javax.swing.JCheckBox ckTieneNumeroSerie;
    private javax.swing.JLabel lbCamposRequeridos;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCosto;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbImpuesto1;
    private javax.swing.JLabel lbImpuesto2;
    private javax.swing.JLabel lbLocalizacion;
    private javax.swing.JLabel lbMonedaCosto;
    private javax.swing.JLabel lbMonedaPrecioUnitario;
    private javax.swing.JLabel lbNivelReorden;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPorcentaje;
    private javax.swing.JLabel lbPorcentaje1;
    private javax.swing.JLabel lbPrecioUnitario;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbUnidadesCantidad;
    private javax.swing.JLabel lbUnidadesReorden;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextField txCategoria;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txCosto;
    private javax.swing.JTextField txDescripcion;
    private javax.swing.JTextField txImpuesto1;
    private javax.swing.JTextField txImpuesto1Cantidad;
    private javax.swing.JTextField txImpuesto2;
    private javax.swing.JTextField txImpuesto2Cantidad;
    private javax.swing.JTextField txLocalizacion;
    private javax.swing.JTextField txNivelReorden;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
