/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controladores.ArrayArticulos;
import javax.swing.ImageIcon;

/**
 *
 * @author Hime
 */
public class frListaArticulos extends javax.swing.JFrame {

    /**
     * Creates new form frListaArticulos
     */
    public frListaArticulos() {
        initComponents();

        try {
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.gif")).getImage());
        } catch (Exception ex) {
             Mensajes.instance.mostrarMensaje("Icono invalido", "No se pudo cargar el icono de la aplicacion.", 0);
        }
        ltArticulos.setListData(ArrayArticulos.getIntancia().getArticulostoArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltArticulos = new javax.swing.JList();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de articulos");
        setResizable(false);

        lbTitulo.setText("Lista de Articulos");
        lbTitulo.setName("lbTitulo"); // NOI18N

        ltArticulos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ltArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ltArticulos.setName("ltArticulos"); // NOI18N
        ltArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickLista(evt);
            }
        });
        jScrollPane2.setViewportView(ltArticulos);
        ltArticulos.getAccessibleContext().setAccessibleName("");

        btnNuevo.setText("Nuevo articulo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar articulo");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnNuevo)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnBuscar)
                    .addComponent(btnCerrar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lbTitulo.getAccessibleContext().setAccessibleName("lbTitulo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClickLista(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickLista
        EditarArticulos ventana = new EditarArticulos(this, true, ltArticulos.getSelectedValue().toString());
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        ltArticulos.setListData(ArrayArticulos.getIntancia().getArticulostoArray());
    }//GEN-LAST:event_ClickLista

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NuevosArticulos ventana = new NuevosArticulos(this, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        ltArticulos.setListData(ArrayArticulos.getIntancia().getArticulostoArray());
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar ventana = new Buscar(null, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        ltArticulos.setListData(ArrayArticulos.getIntancia().getArticulostoArray());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JList ltArticulos;
    // End of variables declaration//GEN-END:variables
}
