/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controladores.ArrayArticulos;
import controladores.ArrayProveedores;
import java.util.List;
import javax.swing.ImageIcon;
import objetos.Articulo;
import objetos.Proveedor;

/**
 *
 * @author Hime
 */
public class NuevosArticulos extends javax.swing.JDialog {

    /**
     * Creates new form NuevosArticulos
     */
    public NuevosArticulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.gif")).getImage());
        } catch (Exception ex) {
            Mensajes.instance.mostrarMensaje("Icono invalido", "No se pudo cargar el icono de la aplicacion.", 0);
        }
        for (Proveedor p1 : ArrayProveedores.getIntancia().getProveedores()) {
            cbProveedores.addItem(p1);
        }
            
        cbProveedores.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCategoria = new javax.swing.JLabel();
        txCategoria = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txDescripcion = new javax.swing.JTextField();
        lbCosto = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txCosto = new javax.swing.JTextField();
        txCodigo = new javax.swing.JTextField();
        lbPrecioUnitario = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        txPrecioUnitario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lbImpuesto1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txImpuesto1 = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        lbCantidad = new javax.swing.JLabel();
        txCantidad = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        lbNivelReorden = new javax.swing.JLabel();
        txNivelReorden = new javax.swing.JTextField();
        lbMonedaCosto = new javax.swing.JLabel();
        lbMonedaPrecioUnitario = new javax.swing.JLabel();
        lbPorcentaje = new javax.swing.JLabel();
        lbUnidadesCantidad = new javax.swing.JLabel();
        lbUnidadesReorden = new javax.swing.JLabel();
        lbProveedor = new javax.swing.JLabel();
        lbCamposRequeridos = new javax.swing.JLabel();
        lbImpuesto2 = new javax.swing.JLabel();
        txImpuesto2 = new javax.swing.JTextField();
        txImpuesto2Cantidad = new javax.swing.JTextField();
        txImpuesto1Cantidad = new javax.swing.JTextField();
        lbPorcentaje1 = new javax.swing.JLabel();
        lbLocalizacion = new javax.swing.JLabel();
        txLocalizacion = new javax.swing.JTextField();
        ckPermiteDescripcionAlterna = new javax.swing.JCheckBox();
        ckTieneNumeroSerie = new javax.swing.JCheckBox();
        cbProveedores = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevos articulos");
        setResizable(false);

        lbCategoria.setForeground(new java.awt.Color(255, 0, 0));
        lbCategoria.setText("*Categoria");

        lbNombre.setForeground(new java.awt.Color(255, 0, 0));
        lbNombre.setText("*Nombre:");

        lbDescripcion.setText("Descripcion");

        txNombre.setToolTipText("Inserte el nombre");

        lbCosto.setForeground(new java.awt.Color(255, 0, 0));
        lbCosto.setText("*Costo:");

        lbCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lbCodigo.setText("*UPC/EAN/ISBN:");

        txCosto.setToolTipText("Inserte el costo");

        lbPrecioUnitario.setForeground(new java.awt.Color(255, 0, 0));
        lbPrecioUnitario.setText("*Precio unitario:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbImpuesto1.setText("Impuesto1:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txImpuesto1.setToolTipText("Inserte el impuesto");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lbCantidad.setText("*Cantidad:");

        txCantidad.setToolTipText("Inserte la cantidad");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lbNivelReorden.setForeground(new java.awt.Color(255, 0, 0));
        lbNivelReorden.setText("*Nivel de reorden:");

        lbMonedaCosto.setText("$");

        lbMonedaPrecioUnitario.setText("$");

        lbPorcentaje.setText("%");

        lbUnidadesCantidad.setText("unidades");

        lbUnidadesReorden.setText("unidades");

        lbProveedor.setForeground(new java.awt.Color(255, 0, 0));
        lbProveedor.setText("*Proveedor");

        lbCamposRequeridos.setText("Los campos con el icono * son requeridos por el sistema");

        lbImpuesto2.setText("Impuesto2:");

        txImpuesto2.setToolTipText("Inserte el impuesto");

        txImpuesto2Cantidad.setToolTipText("Inserte el impuesto");

        txImpuesto1Cantidad.setToolTipText("Inserte el impuesto");

        lbPorcentaje1.setText("%");

        lbLocalizacion.setText("Localizacion");

        ckPermiteDescripcionAlterna.setText("Permite descripción alterna");

        ckTieneNumeroSerie.setText("El artículo tiene numero de serie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDescripcion)
                                .addGap(35, 35, 35)
                                .addComponent(txDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbCategoria)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lbCosto)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbMonedaCosto)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbImpuesto1)
                                                .addGap(34, 34, 34)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbCantidad)
                                            .addGap(36, 36, 36)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbLocalizacion)
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txImpuesto1Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbPorcentaje))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txCantidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbUnidadesCantidad))
                                    .addComponent(txCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txCosto)
                                    .addComponent(txImpuesto1)
                                    .addComponent(txLocalizacion))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPrecioUnitario)
                                        .addGap(25, 25, 25)
                                        .addComponent(lbMonedaPrecioUnitario))
                                    .addComponent(lbNombre)
                                    .addComponent(lbProveedor)
                                    .addComponent(lbImpuesto2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txImpuesto2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txNombre)
                                    .addComponent(txPrecioUnitario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txImpuesto2Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbPorcentaje1))
                                    .addComponent(cbProveedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckTieneNumeroSerie)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ckPermiteDescripcionAlterna)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbNivelReorden)
                                                .addGap(29, 29, 29)
                                                .addComponent(txNivelReorden)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbUnidadesReorden))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCamposRequeridos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCerrar)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigo)
                            .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProveedor)
                            .addComponent(lbCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMonedaCosto)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCosto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbPrecioUnitario)
                                .addComponent(txPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMonedaPrecioUnitario)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbImpuesto1)
                            .addComponent(txImpuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbImpuesto2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txImpuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txImpuesto1Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPorcentaje))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCantidad)
                            .addComponent(txCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txImpuesto2Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPorcentaje1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNivelReorden)
                            .addComponent(txNivelReorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUnidadesReorden)
                            .addComponent(lbUnidadesCantidad))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocalizacion)
                    .addComponent(txLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescripcion)
                            .addComponent(txDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnGuardar)
                            .addComponent(btnCerrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(btnCancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lbCamposRequeridos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckPermiteDescripcionAlterna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckTieneNumeroSerie)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NuevosArticulos ventana = new NuevosArticulos(null, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Buscar ventana = new Buscar(null, true);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Articulo a = new Articulo();
        try {
            
            if(txCodigo.getText().trim().equals(""))
            {
                throw new Exception("El campo codigo esta incompleto.");
            }
            a.UPC = txCodigo.getText().trim();
            
            if(txNombre.getText().trim().equals(""))
            {
                throw new Exception("El nombre del articulo no ha sido especificado.");
            }
            a.nombre = txNombre.getText().trim();
            
            if(txCategoria.getText().trim().equals(""))
            {
                throw new Exception("La categoria del articulo no ha sido especificado.");
            }
            a.categoria = txCategoria.getText().trim();
            
            if(txCosto.getText().trim().equals(""))
            {
                throw new Exception("El costo del articulo no ha sido especificado.");
            }
            try {
                a.costo = Double.parseDouble(txCosto.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El costo es un campo numerico.");
            }
            
            if(txPrecioUnitario.getText().trim().equals(""))
            {
                throw new Exception("El precio unitario del articulo no ha sido especificado.");
            }
            try {
                a.precioUnitario = Double.parseDouble(txPrecioUnitario.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El precio unitario es un campo numerico.");
            }
            
            a.impuesto1 = txImpuesto1.getText().trim();
            try {
                a.impuesto1Cantidad = Double.parseDouble(0 + txImpuesto1Cantidad.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El impuesto de venta es un campo numerico.");
            }
            
            a.impuesto2 = txImpuesto2.getText().trim();
            try {
                a.impuesto2Cantidad = Double.parseDouble(0 + txImpuesto2Cantidad.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El impuesto de venta es un campo numerico.");
            }
            
            if(txCantidad.getText().trim().equals(""))
            {
                throw new Exception("La cantidad del articulo no ha sido especificado.");
            }
            try {
                 a.cantidad = Integer.parseInt(txCantidad.getText());
            } catch (NumberFormatException e) {
                throw new Exception("La cantidad  de venta es un campo numerico entero.");
            }
           
            if(txNivelReorden.getText().trim().equals(""))
            {
                throw new Exception("El nivel de reorden del articulo no ha sido especificado.");
            }
            try {
                 a.nivelReorden = Integer.parseInt(txNivelReorden.getText());
            } catch (NumberFormatException e) {
                throw new Exception("El nivel de reorden es un campo numerico entero.");
            }
            
            a.localizacion = txLocalizacion.getText();
            a.descripcion = txDescripcion.getText();
            a.permitirDescripcionAlterna = ckPermiteDescripcionAlterna.isSelected();
            a.tieneNumeroSerie = ckTieneNumeroSerie.isSelected();

            a.proveedor = ArrayProveedores.getIntancia().devolverProveedor(cbProveedores.getSelectedIndex());
            
            ArrayArticulos.getIntancia().insertarArticulos(a);
            
            Mensajes.instance.mostrarMensaje("Operacion exitosa", "Datos guardados con exito", 1);
            
            this.dispose();
        } catch (Exception ex) {
             Mensajes.instance.mostrarMensaje(ex.getMessage(), "Error", 0);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        txCodigo.setText("");
        txNombre.setText("");
        txCategoria.setText("");
        txCosto.setText("");
        txPrecioUnitario.setText("");
        txImpuesto1.setText("");
        txImpuesto1Cantidad.setText("");
        txImpuesto2.setText("");
        txImpuesto2Cantidad.setText("");
        txCantidad.setText("");
        txNivelReorden.setText("");
        txDescripcion.setText("");
        txLocalizacion.setText("");
        ckPermiteDescripcionAlterna.setSelected(false);
        ckTieneNumeroSerie.setSelected(false);
        cbProveedores.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cbProveedores;
    private javax.swing.JCheckBox ckPermiteDescripcionAlterna;
    private javax.swing.JCheckBox ckTieneNumeroSerie;
    private javax.swing.JLabel lbCamposRequeridos;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCosto;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbImpuesto1;
    private javax.swing.JLabel lbImpuesto2;
    private javax.swing.JLabel lbLocalizacion;
    private javax.swing.JLabel lbMonedaCosto;
    private javax.swing.JLabel lbMonedaPrecioUnitario;
    private javax.swing.JLabel lbNivelReorden;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPorcentaje;
    private javax.swing.JLabel lbPorcentaje1;
    private javax.swing.JLabel lbPrecioUnitario;
    private javax.swing.JLabel lbProveedor;
    private javax.swing.JLabel lbUnidadesCantidad;
    private javax.swing.JLabel lbUnidadesReorden;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextField txCategoria;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txCosto;
    private javax.swing.JTextField txDescripcion;
    private javax.swing.JTextField txImpuesto1;
    private javax.swing.JTextField txImpuesto1Cantidad;
    private javax.swing.JTextField txImpuesto2;
    private javax.swing.JTextField txImpuesto2Cantidad;
    private javax.swing.JTextField txLocalizacion;
    private javax.swing.JTextField txNivelReorden;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
